/** Architectural grammars. All names, motifs and buildings are fictional.
 * Geographical inputs are read-only constraints, not demands on the parent world.
 * A recipe is the stable asset identifier: same version + seed + recipe => same mesh.
 */
const LandmarkCatalog = (() => {
  const styles = [
    {id:'river',name:'River Crown',subtitle:'Courts of the fertile lowlands',type:'palace',color:'#ab604b',icon:'♜',climate:'Temperate river plain',description:'A terraced royal residence with an axial approach, red-roofed galleries, corner pavilions, arcaded courts and geometrical gardens.',parts:'Royal hall · paired wings · water garden · processional gate',material:'limestone',culture:'Human courts',faith:'sun'},
    {id:'basilica',name:'Sanctuary of the Dawn',subtitle:'The sacred city within the city',type:'palace',color:'#b29547',icon:'☼',climate:'Mild uplands',description:'A cruciform sanctuary, ribbed gilded dome, twin campaniles and cloister courts organized around a ceremonial stair.',parts:'Basilica · dome · bell towers · cloisters · pilgrim stair',material:'ivory',culture:'Human courts',faith:'sun'},
    {id:'arcane',name:'The Aether Collegium',subtitle:'An architecture of suspended light',type:'palace',color:'#6c88ad',icon:'✧',climate:'High plateau',description:'An open-ring college surrounds a resonator court. Slender observatories, crystal crowns and elevated galleries form an unmistakable skyline.',parts:'Resonator · observatories · sky galleries · rune court',material:'moonstone',culture:'Mixed traditions',faith:'stars'},
    {id:'forest',name:'The Verdant Court',subtitle:'Halls beneath the living canopy',type:'palace',color:'#578361',icon:'♧',climate:'Moist woodland',description:'Timber courts and pointed pavilions are threaded around great trees, with root buttresses, canopy walks and shaded water gardens.',parts:'Great trees · leaf halls · canopy bridges · root court',material:'woodland',culture:'Elven craft',faith:'grove'},
    {id:'mountain',name:'The Deepgate Holds',subtitle:'A palace cut into the escarpment',type:'palace',color:'#7c817f',icon:'▲',climate:'Rocky highlands',description:'Successive bastioned terraces climb toward a colossal recessed portal, with angular buttresses, mountain halls and a narrow approach bridge.',parts:'Stone gate · upper halls · bastions · ramp · cliff',material:'granite',culture:'Dwarven craft',faith:'hearth'},
    {id:'desert',name:'The Saffron Diwan',subtitle:'Shade, stone and guarded water',type:'palace',color:'#c09555',icon:'◇',climate:'Arid oasis',description:'An enclosed courtyard palace uses wind towers, deep arcades and layered earth-coloured walls. Water features appear only with a supported supply.',parts:'Audience court · wind towers · arcades · reservoir',material:'sandstone',culture:'Human courts',faith:'tide'},
    {id:'delta',name:'The Reedwater Assembly',subtitle:'A palace above the floodplain',type:'palace',color:'#588e8a',icon:'≈',climate:'Lake margin / wetland',description:'Raised long halls and reed-roofed pavilions are linked by boardwalks; canals, boats and landing stages replace the formal avenue.',parts:'Assembly hall · stilt courts · walkways · landings',material:'reed',culture:'Riverfolk craft',faith:'tide'},
    {id:'basalt',name:'The Obsidian Citadel',subtitle:'Heavy walls on an ancient lava field',type:'palace',color:'#82737b',icon:'⬟',climate:'Volcanic bedrock',description:'A quiet basalt fortress, not a palace sitting in lava. Stepped black terraces, copper roofs and a strongly buttressed keep face a protected forecourt.',parts:'Tiered keep · bastions · gate · geothermal court',material:'basalt',culture:'Mixed traditions',faith:'hearth'},
    {id:'fjord',name:'The Whitewake Hall',subtitle:'A northern court facing the water',type:'palace',color:'#6c8996',icon:'❄',climate:'Cold coast',description:'Steep layered roofs, timber arcades and stone watchtowers step down toward a fjord-side landing. Snow and maritime fittings respond to the setting.',parts:'High longhall · watchtowers · covered gallery · quay',material:'northern',culture:'Clan craft',faith:'ancestors'},
    {id:'steppe',name:'The Windward Standard',subtitle:'A moot on the open grassland',type:'palace',color:'#b0a068',icon:'⌖',climate:'Semi-arid grassland',description:'A low ring of felted timber halls around a standing mast court. Wide droving lanes, stock pens and windbreak screens replace a formal avenue.',parts:'Standard court \u00b7 felt halls \u00b7 stock pens \u00b7 windbreaks',material:'steppe',culture:'Clan craft',faith:'ancestors'},
    {id:'paddy',name:'The Sluicewater Prefecture',subtitle:'Courts above the terraced water',type:'palace',color:'#7d9d6b',icon:'\u2635',climate:'Warm fertile valley',description:'Deep-eaved veranda halls step down a terraced slope. Timber galleries, sluice courts and irrigation basins organise the whole precinct.',parts:'Veranda halls \u00b7 sluice court \u00b7 terraces \u00b7 water stair',material:'paddy',culture:'Riverfolk craft',faith:'tide'},
    {id:'delve',name:'The Lamplit Warrens',subtitle:'A hall built around the shaft',type:'palace',color:'#8a7f74',icon:'\u26cf',climate:'Ore-bearing uplands',description:'A stone counting hall and lamp shrine wrap a timber headframe. Spoil terraces, ore chutes and winding gear are the architecture, not decoration.',parts:'Headframe \u00b7 counting hall \u00b7 lamp shrine \u00b7 spoil terraces',material:'delve',culture:'Dwarven craft',faith:'hearth'},
    {id:'lagoon',name:'The Tidewater Chancery',subtitle:'A court reached by water',type:'palace',color:'#6fa3a0',icon:'\u224b',climate:'Warm sheltered lagoon',description:'Arcaded chancery ranges face a walled basin. Canals, mooring steps and shaded loggias take the place of a land approach.',parts:'Chancery ranges \u00b7 walled basin \u00b7 loggias \u00b7 mooring steps',material:'lagoon',culture:'Mixed traditions',faith:'tide'},
    {id:'taiga',name:'The Winterhold Moot',subtitle:'A hall banked against the snow',type:'palace',color:'#7d8f8c',icon:'\u2603',climate:'Cold conifer interior',description:'A long log moot-hall under a very steep shingled roof, with a stave tower, banked earth walls, covered wood stores and a split-log palisade. Snow is shed, not decorated.',parts:'Log moot-hall \u00b7 stave tower \u00b7 wood stores \u00b7 palisade',material:'taiga',culture:'Clan craft',faith:'ancestors'},
    {id:'monsoon',name:'The Rainpavilion Assembly',subtitle:'Halls lifted clear of the wet season',type:'palace',color:'#6f9a63',icon:'\u2602',climate:'Hot perhumid forest',description:'Assembly pavilions stand on hardwood posts under very deep thatched eaves, joined by raised plank walkways. Openings are screens, not glazing; the flood is lived with rather than drained.',parts:'Raised pavilions \u00b7 deep eaves \u00b7 plank walks \u00b7 screen halls',material:'monsoon',culture:'Riverfolk craft',faith:'grove'},
    {id:'lighthouse',name:'The Lantern of Nacre',subtitle:'A landmark of the sea roads',type:'landmark',color:'#669799',icon:'◉',climate:'Coastal headland',description:'A tiered lighthouse with an open lantern chamber, a keeper courtyard, sea stair and signal mast.',parts:'Lantern · tower · keeper court · landing',material:'limestone',culture:'Mixed traditions',faith:'tide'},
    {id:'observatory',name:'The Meridian Orrery',subtitle:'A sanctuary for the moving sky',type:'landmark',color:'#72819b',icon:'✶',climate:'Dry elevated ground',description:'A great three-dimensional armillary sphere crowns stepped astronomical terraces and a crescent-shaped gallery.',parts:'Armillary · instrument terrace · archive · stair',material:'moonstone',culture:'Mixed traditions',faith:'stars'},
    {id:'labyrinth',name:'The Ninth Stair',subtitle:'A threshold beneath the earth',type:'landmark',color:'#a58961',icon:'▥',climate:'Dry rocky interior',description:'An excavated stepped court leads to a monumental subterranean portal. Side pylons, buttresses and survey shelters mark its surface precinct.',parts:'Descending court · sealed portal · pylons · field camp',material:'sandstone',culture:'Dwarven craft',faith:'ancestors'},
    {id:'bridge',name:'The Crownspan',subtitle:'A crossing rather than a barrier',type:'landmark',color:'#819078',icon:'⌒',climate:'River crossing',description:'A multi-arched viaduct with inhabited gatehouses, a way-shrine and a raised parapet walk.',parts:'Viaduct · gatehouses · shrine · river piers',material:'limestone',culture:'Human courts',faith:'sun'},
    {id:'ice',name:'The Pale Archive',subtitle:'A memory kept at the ice margin',type:'landmark',color:'#8bafb7',icon:'✻',climate:'Glacier margin',description:'An insulated archive hall and crystalline signal tower above a cold rock platform. Ice is scenography; no new habitable city is invented.',parts:'Archive · signal · covered walk · glacial rock',material:'northern',culture:'Mixed traditions',faith:'stars'},
    {id:'grove',name:'The Rootbound Shrine',subtitle:'A meeting place in the woodland',type:'landmark',color:'#6b8b63',icon:'♧',climate:'Forest clearing',description:'A monumental tree shelters an open ritual circle, a small organic pavilion and timber approach walks.',parts:'Ancient tree · circle · shrine pavilion · root bridges',material:'woodland',culture:'Elven craft',faith:'grove'}
  ];
  const palettes = {
    limestone:{wall:'#e1d4b5',trim:'#f2e8d1',roof:'#ae624e',metal:'#c0a364',wood:'#80614e',dark:'#4e5c60',ground:'#a9b386',water:'#76b9bd',leaf:'#628659'},
    ivory:{wall:'#e4dfcc',trim:'#f5edd7',roof:'#a9674d',metal:'#c7a552',wood:'#816957',dark:'#596067',ground:'#adb791',water:'#85bbb9',leaf:'#64876b'},
    moonstone:{wall:'#c6d2df',trim:'#eef1e7',roof:'#557a9f',metal:'#c3b47f',wood:'#7f8799',dark:'#455d7b',ground:'#9cafab',water:'#77bdce',leaf:'#668f8c'},
    woodland:{wall:'#c3d1ac',trim:'#e4dfbf',roof:'#4b8776',metal:'#c5ad74',wood:'#826b4c',dark:'#48675d',ground:'#8aa271',water:'#8dc6b8',leaf:'#4f8259'},
    granite:{wall:'#828d91',trim:'#b0b4a8',roof:'#5f757b',metal:'#b59a68',wood:'#736657',dark:'#3d5159',ground:'#91917e',water:'#6f9aa6',leaf:'#5b7964'},
    sandstone:{wall:'#d7b680',trim:'#edd4a4',roof:'#578f88',metal:'#c99f59',wood:'#967957',dark:'#716055',ground:'#d2bc91',water:'#64bcb8',leaf:'#7a9b67'},
    reed:{wall:'#bea674',trim:'#e0d1a0',roof:'#a69659',metal:'#9eb5a0',wood:'#8b7151',dark:'#476f6c',ground:'#849c70',water:'#7bb6b1',leaf:'#527f62'},
    basalt:{wall:'#5c606c',trim:'#9b928f',roof:'#856d61',metal:'#c59767',wood:'#75675c',dark:'#343f51',ground:'#93948e',water:'#769b9f',leaf:'#718370'},
    northern:{wall:'#b9c7c8',trim:'#e6eded',roof:'#536878',metal:'#b3ac8d',wood:'#796b59',dark:'#4b6174',ground:'#b1c6c9',water:'#709eae',leaf:'#537775'},
    steppe:{wall:'#d5c69c',trim:'#efe3c0',roof:'#8f7a52',metal:'#bda162',wood:'#7d6748',dark:'#4f4a3c',ground:'#bdb684',water:'#7fb0a6',leaf:'#8a9a5e'},
    paddy:{wall:'#dcd6c0',trim:'#f0ead2',roof:'#5b7a5a',metal:'#b9a46a',wood:'#6f5842',dark:'#3f4d45',ground:'#94a878',water:'#84c0b4',leaf:'#4d8455'},
    delve:{wall:'#8d8781',trim:'#bab2a4',roof:'#6a5b52',metal:'#c9a05c',wood:'#6b5b4a',dark:'#38363a',ground:'#8f8a80',water:'#7ba0a5',leaf:'#5e7561'},
    lagoon:{wall:'#e0d7c2',trim:'#f4ecd8',roof:'#3f8b91',metal:'#c7ab63',wood:'#7c6650',dark:'#40575e',ground:'#b0b593',water:'#6cc0c4',leaf:'#5f8a6a'},
    // Weathered log and wet shingle under snow-pale trim.
    taiga:{wall:'#a08a6c',trim:'#dcd7c6',roof:'#465a63',metal:'#a7a086',wood:'#6a5339',dark:'#31373a',ground:'#8e9a92',water:'#7aa4b0',leaf:'#3d6a63'},
    // Lime-washed screen walls, hardwood posts and thatch.
    monsoon:{wall:'#e5dec6',trim:'#f4eeda',roof:'#9a7943',metal:'#c0a45f',wood:'#5d4833',dark:'#38453e',ground:'#7d9367',water:'#6fbfb2',leaf:'#2f7146'}
  };
  const faiths={sun:{label:'Dawn Covenant',motif:'Sun disks and radial processional courts'},stars:{label:'Celestial Compact',motif:'Armillary rings, crystals and observatory crowns'},grove:{label:'Grove Accord',motif:'Branching finials, living trees and open shrines'},hearth:{label:'Hearth Tradition',motif:'Brazier courts, angular buttresses and hearth symbols'},tide:{label:'Tidal Way',motif:'Wave crests, stepped basins and open waterfront courts'},ancestors:{label:'Ancestor Rites',motif:'Memorial pillars, long halls and family standards'},secular:{label:'Civic / plural',motif:'Public emblems, banners and assembly spaces'}};
  function hash(s){let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
  function rng(seed){let a=hash(seed);return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
  function recipe(style='river',seed='AERETH / 01',overrides={}) {
    const s=styles.find(t=>t.id===style)||styles[0],r=rng(seed+style);
    const result={format:'telluric-landmark-recipe',version:1,id:overrides.id||'library-'+s.id,style:s.id,seed:String(seed).slice(0,120),name:s.name,material:s.material,faith:s.faith,culture:s.culture,complexity:2,crown:'native',roofLanguage:'native',variant:Math.floor(r()*3),wings:2+Math.floor(r()*2),roofPitch:.85+r()*.28,ornament:r()>.45?'radial':'braided',geography:{freshwater:.9,coast:['fjord','lighthouse'].includes(style),lake:style==='delta',cold:['fjord','ice','taiga'].includes(style),dry:['desert','labyrinth'].includes(style),forest:['forest','grove','taiga','monsoon'].includes(style),elevation:['mountain','basalt','ice'].includes(style)?1800:350},provenance:'Template-library specimen; surrounding terrain is an illustrative stage, not a new world cell.',...overrides};
    if(!palettes[result.material])result.material=s.material;if(!faiths[result.faith])result.faith=s.faith;
    if(!['native','spire','dome','crystal','battlement'].includes(result.crown))result.crown='native';if(!['native','hip','gable','flat','leaf','northern'].includes(result.roofLanguage))result.roofLanguage='native';result.roofPitch=Math.max(.65,Math.min(1.6,Number(result.roofPitch)||1));result.geography={...(result.geography||{}),freshwater:Math.max(0,Math.min(1,Number(result.geography?.freshwater)||0))};if(result.geography.cold&&result.roofLanguage==='flat')result.roofLanguage='northern';
    result.variant=Math.abs(Math.floor(Number(result.variant)||0))%4;result.complexity=Math.max(0,Math.min(2,Number(result.complexity)||0));return result;
  }
  function fromProvince(w,sim,p,kind='civic',buildingId=''){
    const site=CityEnvironment.profile(w,p),c=sim.realms[p.owner],people=p.people?.indexOf(Math.max(...p.people))||0,faith=p.faith?.indexOf(Math.max(...p.faith))||0;
    let style=kind==='academy'?'arcane':kind==='temple'?'basilica':kind==='harbor'?'lighthouse':'river';
    if(kind==='civic'){
      if(site.glacialFoothills||site.bed>1450)style='mountain';else if(p.wet>.2||p.siteLake>.6)style='delta';else if(site.temperature<5&&p.harbor>.12)style='fjord';else if(site.aridity<.65&&site.temperature>=16)style='desert';else if(p.forest>.48&&people===1)style='forest';else if((w.arc[p.i]>.5||w.rift[p.i]>.8)&&p.ore>.4)style='basalt';else if(c?.gov===2)style='arcane';else if(c?.gov===1)style='basilica';
    }
    if(kind==='temple'&&faith===2&&p.forest>.25)style='grove';
    const cultures=['Human courts','Elven craft','Dwarven craft','Clan craft','Mixed traditions','Riverfolk craft','Drake craft'];
    const f=['sun','stars','grove','hearth','tide','secular'][faith]||'secular';
    let material=styles.find(t=>t.id===style).material;if(site.glacialFoothills)material='granite';else if(site.aridity<.65&&site.temperature>=16)material='sandstone';else if(site.temperature<3)material='northern';
    return recipe(style,`${w.params.seed}/place/${p.i}/${kind}/${buildingId}`,{id:`site-${p.id}-${kind}-${buildingId}`,name:`${p.name} · ${kind==='civic'?(c?.gov===2?'High Collegium':c?.gov===1?'Sanctuary Palace':'Civic Palace'):kind==='temple'?'Great Sanctuary':kind==='academy'?'Star College':'Harbor Beacon'}`,material,faith:f,culture:cultures[people]||'Mixed traditions',provinceId:p.id,kind,buildingId,realm:c?.name||'Local communities',geography:{freshwater:p.fresh||0,coast:(p.harbor||0)>.18,lake:(p.siteLake||0)>.25,cold:site.temperature<3,dry:site.aridity<.65,forest:site.forestFraction>.4,elevation:site.bed,sourceCell:p.i,setting:site.label},provenance:`Reads existing settlement ${p.name}, local climate, construction tradition and local faith. The detailed precinct is synthesized; it does not alter its city, population or coastline.`});
  }
  function signature(r){return hash(JSON.stringify([r.version,r.style,r.seed,r.material,r.faith,r.culture,r.variant,r.wings,r.roofPitch,r.crown,r.roofLanguage,r.geography,r.sacred||false,r.sacredVersion||0])).toString(16).padStart(8,'0')}
  function validate(r){if(!r||r.format!=='telluric-landmark-recipe'||r.version!==1)throw Error('Unsupported landmark recipe.');if(!styles.some(s=>s.id===r.style))throw Error('Unknown template.');if(typeof r.seed!=='string'||r.seed.length>120)throw Error('Invalid design seed.');if(!palettes[r.material]||!faiths[r.faith])throw Error('Unknown material or ritual motif.');return recipe(r.style,r.seed,r)}
  return {styles,palettes,faiths,recipe,fromProvince,signature,validate,rng,hash};
})();
if(typeof module!=='undefined')module.exports=LandmarkCatalog;
