export const scripts = [
    'src/world/geography.js',
    'src/civilization/realm-names.js', 'src/civilization/simulation.js',
    'src/world/roads.js',
    'src/civilization/folk.js',
    'src/civilization/portrait.js',
    'src/civilization/saga.js',
    'src/city/environment.js', 'src/towns/catalog.js',
    'src/towns/vocabulary.js',
    'src/towns/grammar.js', 'src/towns/fortifications.js',
    'src/city/generator.js',
    'src/city/actions.js',
    'src/render/world-renderer.js',
    'src/render/road-renderer.js',
    'src/render/folk-renderer.js',
    'src/landmarks/catalog.js',
    'src/landmarks/kit.js',
    'src/landmarks/templates.js',
    'src/landmarks/world-binding.js',
    'src/render/depth-rasterizer.js',
    'src/towns/building-kit.js', 'src/towns/artisan-kit.js',
    'src/towns/wonders-woodland.js', 'src/towns/wonders-stone.js', 'src/towns/wonders-arcane.js',
    'src/towns/sacred-kit.js',
    'src/render/city-renderer.js',
    'src/continuous/atlas-space.js', 'src/continuous/city-layer.js',
    'src/render/landmark-renderer.js',
    'src/render/export-glb.js',
    'src/ui/world-ui.js',
    'src/ui/city-ui.js',
    'src/ui/landmark-ui.js',
    'src/ui/onemap-ui.js',
    'src/continuous/generated-worker.js',
    'src/ui/continuous-map.js',
    'src/bootstrap.js',
];
export const styles = ['styles/world.css', 'styles/city.css', 'styles/landmarks.css', 'styles/towns.css', 'styles/onemap.css', 'styles/continuous.css'];
