/** Compare authored street blocks on one immutable, real town layout. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {deserialize} from 'node:v8';
import {createHash} from 'node:crypto';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {scripts} from './manifest.mjs';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),args=process.argv.slice(2),arg=(name,fallback)=>{const i=args.indexOf(name);return i<0?fallback:args[i+1]};
const baseline=arg('--baseline','9f184036f8daf6f5070919f1351c6eba25343dba'),fixturePath=arg('--fixture',null),output=resolve(root,arg('--output','previews/streets'));
const readPrior=f=>execFileSync('git',['show',baseline+':'+f],{cwd:root,encoding:'utf8',maxBuffer:8e6});
const oldManifest=readPrior('scripts/manifest.mjs'),oldFiles=Function(oldManifest.replaceAll('export const','const')+';return scripts;')();
const before=oldFiles.slice(0,oldFiles.indexOf('src/ui/world-ui.js')).map(readPrior).join('\n');
const after=await Promise.all(scripts.slice(0,scripts.indexOf('src/ui/world-ui.js')).map(f=>readFile(resolve(root,f),'utf8'))).then(a=>a.join('\n'));
const exports='return {Geometry,ArtisanCityKit,CityEnvironment,createLandmarkRenderer,cityStreetMesh,cityFootingMesh,rgb,colorMix,clamp,mul4,ortho,lookAt,generateWorld,createCivilization,generateCity,auditCity,physicalFingerprint,settlementFingerprint,politicalFingerprint};';
const Before=Function(before+'\n'+exports)();
let fixture;if(fixturePath)fixture=deserialize(await readFile(fixturePath));else{const params={seed:'Aereth-47',form:'global',plates:24,continents:6,islands:1.2,volcanism:.85,uplift:1.2,sea:0,aridity:.85,current:1,erosion:.7,temperature:0,glaciation:1.2,landformVersion:3},w=await Before.generateWorld(params),s=Before.createCivilization(w,{realms:18,conflict:1,historySeed:'First-dawn'});fixture={w,s,cities:[529,496,463].map(id=>({p:s.provinces[id],c:Before.generateCity(w,s,id)}))}}
function reviveCity(c){c.xy=i=>({x:(i%c.n/(c.n-1)-.5)*c.width,z:(Math.floor(i/c.n)/(c.n-1)-.5)*c.depth});c.index=(x,z)=>Math.max(0,Math.min(c.n-1,Math.round((z/c.depth+.5)*(c.n-1))))*c.n+Math.max(0,Math.min(c.n-1,Math.round((x/c.width+.5)*(c.n-1))));return c}
function select(c){
 const lots=c.buildings.filter(b=>!b.landmark&&['home','market','workshop'].includes(b.program)),byId=new Map(c.connectors.map(q=>[q.blockId,q]));
 const choices=lots.filter(b=>b.program==='home'&&Math.min(b.w,b.d)>1.1&&(byId.get(b.id)?.dist??100)<2.5).map(b=>{const near=lots.filter(q=>Math.hypot(q.x-b.x,q.z-b.z)<12);return{b,near,score:near.filter(q=>q.program==='market'||q.program==='workshop').length*5+Math.min(10,near.length)-Math.hypot(b.x,b.z)*.03-(b.terrainFall||0)}}).sort((a,b)=>b.score-a.score);
 if(!choices.length)throw Error(c.name+' has no ordinary street-front sample');const {b,near}=choices[0],ids=near.sort((a,q)=>Math.hypot(a.x-b.x,a.z-b.z)-Math.hypot(q.x-b.x,q.z-b.z)).slice(0,12).map(b=>b.id),q=byId.get(b.id),dx=q.b.x-q.a.x,dz=q.b.z-q.a.z,L=Math.hypot(dx,dz);
 return{focus:b.id,ids,camera:{target:[b.x+dx/L*2,b.y+1.3,b.z+dz/L*2],azimuth:Math.atan2(dx,dz)-.45,elevation:.62,zoom:3.5}};
}
const sha=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const samples=fixture.cities.map(({p,c})=>{reviveCity(c);const selected=select(c),positions=c.buildings.map(b=>[b.id,b.x,b.y,b.z,b.w,b.d,b.h,b.angle,b.streetSocket,b.program,b.module,b.moduleVariant]),audit=Before.auditCity(c);for(const k of['wetBuildings','roadBuildings','overlaps','nonfinite','seaRoads'])if(audit[k])throw Error(c.name+' baseline fails '+k);
 const keep=['version','seed','name','provinceId','n','width','depth','terrainSpan','height','water','waterKind','wet','road','roads','connectors','buildings','townProfile','townRecipe','siteEnvironment','fingerprint','districts'];const city=Object.fromEntries(keep.map(k=>[k,c[k]]));city.environment=Object.fromEntries(['temperature','aridity','bed','ice','snow','winter','color'].map(k=>[k,c.environment[k]]));
 return{p,realm:fixture.s.realms[p.owner],c:city,...selected,layout:{fingerprint:c.fingerprint,parcels:c.buildings.length,positionsHash:sha(positions),positions,audit},temperature:Before.CityEnvironment.profile(fixture.w,p).temperature};});
const fingerprints=[Before.physicalFingerprint(fixture.w),Before.settlementFingerprint(fixture.s),Before.politicalFingerprint(fixture.s)];
function pack(v){if(ArrayBuffer.isView(v))return{$typed:v.constructor.name,data:Buffer.from(v.buffer,v.byteOffset,v.byteLength).toString('base64')};if(Array.isArray(v))return v.map(pack);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).filter(([,x])=>typeof x!=='function'&&x!==undefined).map(([k,x])=>[k,pack(x)]));return v}
function assemble(A,s,lod=2){
 const c=reviveCity(s.c),G=()=>new A.Geometry(),ground=G(),roads=G(),roadDetails=G(),parts=[],selected=c.buildings.filter(b=>s.ids.includes(b.id)),focus=c.buildings.find(b=>b.id===s.focus),radius=17;
 const inside=(x,z)=>Math.abs(x-focus.x)<radius&&Math.abs(z-focus.z)<radius;
 const elevation=(x,z)=>{const gx=Math.max(0,Math.min(c.n-1,(x/c.width+.5)*(c.n-1))),gz=Math.max(0,Math.min(c.n-1,(z/c.depth+.5)*(c.n-1))),i=Math.floor(gx),j=Math.floor(gz),u=gx-i,v=gz-j,at=(x,z)=>c.height[Math.min(c.n-1,z)*c.n+Math.min(c.n-1,x)];return at(i,j)*(1-u)*(1-v)+at(i+1,j)*u*(1-v)+at(i,j+1)*(1-u)*v+at(i+1,j+1)*u*v};
 for(let z=0;z<c.n-1;z++)for(let x=0;x<c.n-1;x++){const ids=[z*c.n+x,z*c.n+x+1,(z+1)*c.n+x,(z+1)*c.n+x+1],ps=ids.map(i=>{const q=c.xy(i);return[q.x,c.height[i],q.z]});if(!ps.some(p=>inside(p[0],p[2])))continue;const col=[0,0,0];for(const i of ids)for(let j=0;j<3;j++)col[j]+=c.environment.color[i*3+j]/4;const snow=ids.reduce((n,i)=>n+A.CityEnvironment.localClimate(c.environment,i).cover/4,0),tone=snow>.05?A.colorMix(col,A.rgb('#e9f1f4'),A.clamp(snow*.85)):col;ground.tri(ps[0],ps[2],ps[1],tone);ground.tri(ps[1],ps[2],ps[3],tone)}
 A.cityStreetMesh(c,elevation,roads,roadDetails);const crop=g=>{const h=G();for(let i=0;i<g.data.length;i+=27)if(inside((g.data[i]+g.data[i+9]+g.data[i+18])/3,(g.data[i+2]+g.data[i+11]+g.data[i+20])/3))h.data.push(...g.data.slice(i,i+27));return h};
 const add=(id,name,role,geometry)=>parts.push({id,name,role,geometry,anchor:[0,0,0]});add('ground','Original surveyed ground','landscape',ground);add('streets','Original streets','landscape',crop(roads));add('bridge-details','Street supports','architecture',crop(roadDetails));
 const lots=[];for(const b0 of selected){const b={...b0,lod},m=A.ArtisanCityKit.compound(b,c,s.p,s.realm),foundation=G();A.cityFootingMesh(foundation,b,m,A.rgb(A.ArtisanCityKit.blockPaint(c,b).wall));add(b.id+'-foundation',b.name+' foundation','architecture',foundation);add(b.id,b.name,'architecture',m.body);add(b.id+'-roof',b.name+' roofs','roof',m.roof);let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const g of[m.body,m.roof])for(let i=0;i<g.data.length;i+=9)for(let j=0;j<3;j++){min[j]=Math.min(min[j],g.data[i+j]);max[j]=Math.max(max[j],g.data[i+j])}lots.push({id:b.id,program:b.program,angle:b.angle,streetSocket:b.streetSocket,triangles:(m.body.data.length+m.roof.data.length)/27,bodyTriangles:m.body.data.length/27,roofTriangles:m.roof.data.length/27,min,max,footprint:[b.x-b.w/2,b.z-b.d/2,b.x+b.w/2,b.z+b.d/2]})}
 const bounds={min:[focus.x-radius,-5,focus.z-radius],max:[focus.x+radius,15,focus.z+radius]};for(const p of parts)p.bounds=bounds;
 return{model:{signature:s.p.id+'/'+lod,recipe:{},parts,bounds},lots,triangles:lots.reduce((n,b)=>n+b.triangles,0)};
}
// Validate the actual historic assemblies now; the updated builder is exercised
// by the same function in the page, including each placed street-facing addition.
for(const s of samples){const model=assemble(Before,s);if(!model.triangles||model.lots.length<3)throw Error('Empty street preview');console.log(s.p.id,s.p.name,s.c.townProfile.id,s.layout.parcels+' parcels',model.lots.length+' shown',model.triangles+' triangles')}
const safe=s=>s.replace(/<\/script/gi,'<\\/script');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Orbis · 住屋与街面</title><style>*{box-sizing:border-box}body{margin:0;background:#142a2a;color:#efecdc;font:14px/1.5 system-ui,sans-serif}header,nav,footer{padding:16px 24px}header{border-bottom:1px solid #435959}h1{margin:3px 0 7px;font:30px/1.2 Georgia,serif}p{margin:4px 0;color:#bdccc6}nav{display:flex;gap:10px;flex-wrap:wrap;align-items:center}label{display:flex;gap:7px;align-items:center}button,select{font:inherit;padding:7px 11px;border:1px solid #6b8079;border-radius:5px;background:#28453f;color:#eee7d1}button{cursor:pointer}button[aria-pressed=true]{background:#e0d9b8;color:#233a33}button:focus-visible,select:focus-visible,canvas:focus-visible{outline:3px solid #b2d4c5;outline-offset:2px}.views{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:#60766c}.panel{background:#e8e9df;min-width:0;color:#29443b}.panel h2{font-size:13px;margin:0;padding:12px 18px}.stage{height:clamp(430px,65vh,720px)}canvas{display:block;width:100%;height:100%;touch-action:none}.metrics{padding:11px 18px;min-height:44px;font-size:12px}footer{display:flex;justify-content:space-between;gap:20px;font-size:12px}.error{color:#ffb896}@media(max-width:750px){header,nav,footer{padding:13px}.views{grid-template-columns:1fr}.stage{height:450px}footer{display:block}}</style><header><h1>住宅与沿街界面对照</h1><p>来自同一座真实城镇的同一组地块。左右共用地面、道路、人口与镜头；只比较建筑模型。</p></header><nav><label>城镇<select id="town">${samples.map(s=>`<option value="${s.p.id}">${s.p.name} · ${s.c.townProfile.short} · ${s.temperature.toFixed(1)}°C</option>`).join('')}</select></label><button data-view="street" aria-pressed="true">沿街</button><button data-view="plan" aria-pressed="false">俯视</button><button data-view="close" aria-pressed="false">住屋近景</button><button id="reset">重置镜头</button><label><input id="roofs" type="checkbox" checked>屋顶</label><label>细节<select id="lod"><option value="2">近景</option><option value="1">中景</option><option value="0">远景</option></select></label></nav><main class="views">${[['Before','原模型 · '+baseline.slice(0,7)],['After','新模型 · 同一地块']].map(([id,label])=>`<section class="panel"><h2>${label}</h2><div class="stage"><canvas id="${id}" tabindex="0" aria-label="${label}，拖动同步旋转"></canvas></div><div class="metrics" id="${id}Stats"></div></section>`).join('')}</main><footer><span id="status" role="status">正在组装真实街区…</span><span>拖动旋转 · Shift拖动平移 · 滚轮缩放 · 镜头始终同步</span></footer>
<script>const Before=(()=>{${safe(before)}\n${exports}})();const After=(()=>{${safe(after)}\n${exports}})();function unpack(v){if(v?.$typed){const raw=atob(v.data),b=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)b[i]=raw.charCodeAt(i);return new globalThis[v.$typed](b.buffer)}if(Array.isArray(v))return v.map(unpack);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,unpack(x)]));return v}const samples=unpack(${safe(JSON.stringify(pack(samples)))});const fingerprints=${JSON.stringify(fingerprints)};const reviveCity=${reviveCity};const assemble=${assemble};</script><script>
const E=id=>document.getElementById(id),stages=[];let active=samples[0],view='street';
function publish(){window.__streetPreview={ready:true,provinceId:active.p.id,focus:active.focus,ids:active.ids,fingerprints,layout:active.layout,cameras:stages.map(s=>({target:s.r.target.slice(),zoom:s.r.zoom,azimuth:s.r.azimuth,elevation:s.r.elevation})),before:stages[0].scene.lots,after:stages[1].scene.lots,roofs:E('roofs').checked,lod:Number(E('lod').value)};}
function light(r){const t=active.camera.target;r.sunDirection=[-.6,1,.8];r.lightVP=After.mul4(After.ortho(-24,24,-24,24,1,140),After.lookAt([t[0]-38,t[1]+56,t[2]+42],t,[0,1,0]));r.dirtyShadow=true;r.request();}
function reset(){for(const s of stages){Object.assign(s.r,active.camera);s.r.target=active.camera.target.slice();if(view==='plan'){s.r.elevation=1.5;s.r.zoom=2.9}else if(view==='close'){s.r.zoom=6.1;s.r.elevation=.45}light(s.r)}document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));publish();}
function load(){try{document.body.dataset.ready='building';active=samples.find(s=>String(s.p.id)===E('town').value)||samples[0];for(const s of stages){s.scene=assemble(s.api,active,Number(E('lod').value));s.r.setModel(s.scene.model);s.r.roofs=E('roofs').checked;E(s.id+'Stats').textContent=s.scene.lots.length+' 块普通住屋与工作院 · '+s.scene.triangles.toLocaleString()+' 个建筑三角形'}reset();E('status').textContent=active.p.name+' · 原布局 '+active.layout.fingerprint+' · '+active.layout.parcels+' 块地块完整保留';document.body.dataset.ready='true'}catch(error){E('status').textContent=error.message;E('status').className='error';document.body.dataset.ready='error';console.error(error)}}
function move(dx,dy,zoom=1,pan=false){for(const s of stages){const r=s.r;if(pan){r.updateCamera();const k=2*r.halfW/r.width;r.target[0]-=dx*k*r.right[0]+dy*k*Math.sin(r.azimuth)/Math.max(.2,Math.sin(r.elevation));r.target[2]-=dx*k*r.right[2]+dy*k*Math.cos(r.azimuth)/Math.max(.2,Math.sin(r.elevation))}else{r.azimuth-=dx*.007;r.elevation=Math.max(.16,Math.min(1.55,r.elevation+dy*.004))}r.zoom=Math.max(.8,Math.min(14,r.zoom*zoom));r.request()}publish()}
for(const[id,api]of[['Before',Before],['After',After]]){const canvas=E(id),r=After.createLandmarkRenderer(canvas),s={id,api,r};stages.push(s);let drag=null;canvas.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;move(e.clientX-drag[0],e.clientY-drag[1],1,e.shiftKey);drag=[e.clientX,e.clientY]});for(const t of['pointerup','pointercancel'])canvas.addEventListener(t,()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();move(0,0,Math.exp(-e.deltaY*.001))},{passive:false});canvas.addEventListener('keydown',e=>{const action={ArrowLeft:[-16,0],ArrowRight:[16,0],ArrowUp:[0,16],ArrowDown:[0,-16],'+':[0,0,1.15],'=':[0,0,1.15],'-':[0,0,1/1.15]}[e.key];if(action){e.preventDefault();move(...action)}})}
E('town').onchange=()=>{view='street';load()};E('lod').onchange=load;E('reset').onclick=reset;E('roofs').onchange=()=>{for(const s of stages){s.r.roofs=E('roofs').checked;s.r.dirtyShadow=true;s.r.request()}publish()};for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{view=b.dataset.view;reset()};window.addEventListener('resize',()=>{for(const s of stages)s.r.resize();reset()});window.__streetRuntime={stages,samples,Before,After,load,reset};load();
</script></html>`;
await mkdir(output,{recursive:true});await writeFile(resolve(output,'index.html'),html);await writeFile(resolve(output,'layout-proof.json'),JSON.stringify({baseline,fingerprints,samples:samples.map(s=>({id:s.p.id,name:s.p.name,style:s.c.townProfile.id,temperature:s.temperature,focus:s.focus,ids:s.ids,camera:s.camera,...s.layout}))},null,2)+'\n');console.log('Built '+output+'/index.html · '+Math.round(Buffer.byteLength(html)/1024)+' KiB');
